name = "MolSimToolkitShared"
uuid = "aea21201-7910-416e-b888-414710bebccb"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
